"""
POSIX utility wrappers for ergonomic shell scripting.

This module provides wrapper functions for POSIX-standard external utilities,
allowing concise command invocation without needing to use prog() explicitly.

Usage:
    from shp.ergo.posix import awk, grep, sed
    
    # Before: prog('awk')('-F', ':', '{print $1}') 
    # After:  awk('-F', ':', '{print $1}')

Note: Shell built-ins like cd, pwd, exit are in shp.ergo.builtins instead.

This file is auto-generated by tools/generate_posix_wrappers.py
"""

from shp import prog, ShipRunnable

__all__ = [
    "admin",
    "ar",
    "asa",
    "at",
    "awk",
    "basename",
    "batch",
    "bc",
    "c99",
    "cal",
    "cat",
    "cflow",
    "chgrp",
    "chmod",
    "chown",
    "cksum",
    "cmp",
    "comm",
    "compress",
    "cp",
    "crontab",
    "csplit",
    "ctags",
    "cut",
    "cxref",
    "date",
    "dd",
    "delta",
    "df",
    "diff",
    "dirname",
    "du",
    "ed",
    "env",
    "ex",
    "expand",
    "expr",
    "file",
    "find",
    "fold",
    "fort77",
    "fuser",
    "gencat",
    "get",
    "getconf",
    "grep",
    "head",
    "iconv",
    "id",
    "ipcrm",
    "ipcs",
    "join",
    "lex",
    "link",
    "ln",
    "locale",
    "localedef",
    "logger",
    "logname",
    "lp",
    "ls",
    "m4",
    "mailx",
    "make",
    "man",
    "mesg",
    "mkdir",
    "mkfifo",
    "more",
    "mv",
    "newgrp",
    "nice",
    "nl",
    "nm",
    "nohup",
    "od",
    "paste",
    "patch",
    "pathchk",
    "pax",
    "pr",
    "printf",
    "prs",
    "ps",
    "qalter",
    "qdel",
    "qhold",
    "qmove",
    "qmsg",
    "qrerun",
    "qrls",
    "qselect",
    "qsig",
    "qstat",
    "qsub",
    "renice",
    "rm",
    "rmdel",
    "rmdir",
    "sact",
    "sccs",
    "sed",
    "sleep",
    "sort",
    "split",
    "strings",
    "strip",
    "stty",
    "tabs",
    "tail",
    "talk",
    "tee",
    "time",
    "touch",
    "tput",
    "tr",
    "tsort",
    "tty",
    "uname",
    "uncompress",
    "unexpand",
    "unget",
    "uniq",
    "unlink",
    "uucp",
    "uudecode",
    "uuencode",
    "uustat",
    "uux",
    "val",
    "vi",
    "wc",
    "what",
    "who",
    "write",
    "xargs",
    "yacc",
    "zcat"
]


def admin(*args: str) -> ShipRunnable:
    """Execute POSIX utility "admin"."""
    return prog("admin")(*args)


def ar(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ar"."""
    return prog("ar")(*args)


def asa(*args: str) -> ShipRunnable:
    """Execute POSIX utility "asa"."""
    return prog("asa")(*args)


def at(*args: str) -> ShipRunnable:
    """Execute POSIX utility "at"."""
    return prog("at")(*args)


def awk(*args: str) -> ShipRunnable:
    """Execute POSIX utility "awk"."""
    return prog("awk")(*args)


def basename(*args: str) -> ShipRunnable:
    """Execute POSIX utility "basename"."""
    return prog("basename")(*args)


def batch(*args: str) -> ShipRunnable:
    """Execute POSIX utility "batch"."""
    return prog("batch")(*args)


def bc(*args: str) -> ShipRunnable:
    """Execute POSIX utility "bc"."""
    return prog("bc")(*args)


def c99(*args: str) -> ShipRunnable:
    """Execute POSIX utility "c99"."""
    return prog("c99")(*args)


def cal(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cal"."""
    return prog("cal")(*args)


def cat(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cat"."""
    return prog("cat")(*args)


def cflow(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cflow"."""
    return prog("cflow")(*args)


def chgrp(*args: str) -> ShipRunnable:
    """Execute POSIX utility "chgrp"."""
    return prog("chgrp")(*args)


def chmod(*args: str) -> ShipRunnable:
    """Execute POSIX utility "chmod"."""
    return prog("chmod")(*args)


def chown(*args: str) -> ShipRunnable:
    """Execute POSIX utility "chown"."""
    return prog("chown")(*args)


def cksum(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cksum"."""
    return prog("cksum")(*args)


def cmp(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cmp"."""
    return prog("cmp")(*args)


def comm(*args: str) -> ShipRunnable:
    """Execute POSIX utility "comm"."""
    return prog("comm")(*args)


def compress(*args: str) -> ShipRunnable:
    """Execute POSIX utility "compress"."""
    return prog("compress")(*args)


def cp(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cp"."""
    return prog("cp")(*args)


def crontab(*args: str) -> ShipRunnable:
    """Execute POSIX utility "crontab"."""
    return prog("crontab")(*args)


def csplit(*args: str) -> ShipRunnable:
    """Execute POSIX utility "csplit"."""
    return prog("csplit")(*args)


def ctags(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ctags"."""
    return prog("ctags")(*args)


def cut(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cut"."""
    return prog("cut")(*args)


def cxref(*args: str) -> ShipRunnable:
    """Execute POSIX utility "cxref"."""
    return prog("cxref")(*args)


def date(*args: str) -> ShipRunnable:
    """Execute POSIX utility "date"."""
    return prog("date")(*args)


def dd(*args: str) -> ShipRunnable:
    """Execute POSIX utility "dd"."""
    return prog("dd")(*args)


def delta(*args: str) -> ShipRunnable:
    """Execute POSIX utility "delta"."""
    return prog("delta")(*args)


def df(*args: str) -> ShipRunnable:
    """Execute POSIX utility "df"."""
    return prog("df")(*args)


def diff(*args: str) -> ShipRunnable:
    """Execute POSIX utility "diff"."""
    return prog("diff")(*args)


def dirname(*args: str) -> ShipRunnable:
    """Execute POSIX utility "dirname"."""
    return prog("dirname")(*args)


def du(*args: str) -> ShipRunnable:
    """Execute POSIX utility "du"."""
    return prog("du")(*args)


def ed(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ed"."""
    return prog("ed")(*args)


def env(*args: str) -> ShipRunnable:
    """Execute POSIX utility "env"."""
    return prog("env")(*args)


def ex(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ex"."""
    return prog("ex")(*args)


def expand(*args: str) -> ShipRunnable:
    """Execute POSIX utility "expand"."""
    return prog("expand")(*args)


def expr(*args: str) -> ShipRunnable:
    """Execute POSIX utility "expr"."""
    return prog("expr")(*args)


def file(*args: str) -> ShipRunnable:
    """Execute POSIX utility "file"."""
    return prog("file")(*args)


def find(*args: str) -> ShipRunnable:
    """Execute POSIX utility "find"."""
    return prog("find")(*args)


def fold(*args: str) -> ShipRunnable:
    """Execute POSIX utility "fold"."""
    return prog("fold")(*args)


def fort77(*args: str) -> ShipRunnable:
    """Execute POSIX utility "fort77"."""
    return prog("fort77")(*args)


def fuser(*args: str) -> ShipRunnable:
    """Execute POSIX utility "fuser"."""
    return prog("fuser")(*args)


def gencat(*args: str) -> ShipRunnable:
    """Execute POSIX utility "gencat"."""
    return prog("gencat")(*args)


def get(*args: str) -> ShipRunnable:
    """Execute POSIX utility "get"."""
    return prog("get")(*args)


def getconf(*args: str) -> ShipRunnable:
    """Execute POSIX utility "getconf"."""
    return prog("getconf")(*args)


def grep(*args: str) -> ShipRunnable:
    """Execute POSIX utility "grep"."""
    return prog("grep")(*args)


def head(*args: str) -> ShipRunnable:
    """Execute POSIX utility "head"."""
    return prog("head")(*args)


def iconv(*args: str) -> ShipRunnable:
    """Execute POSIX utility "iconv"."""
    return prog("iconv")(*args)


def id(*args: str) -> ShipRunnable:
    """Execute POSIX utility "id"."""
    return prog("id")(*args)


def ipcrm(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ipcrm"."""
    return prog("ipcrm")(*args)


def ipcs(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ipcs"."""
    return prog("ipcs")(*args)


def join(*args: str) -> ShipRunnable:
    """Execute POSIX utility "join"."""
    return prog("join")(*args)


def lex(*args: str) -> ShipRunnable:
    """Execute POSIX utility "lex"."""
    return prog("lex")(*args)


def link(*args: str) -> ShipRunnable:
    """Execute POSIX utility "link"."""
    return prog("link")(*args)


def ln(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ln"."""
    return prog("ln")(*args)


def locale(*args: str) -> ShipRunnable:
    """Execute POSIX utility "locale"."""
    return prog("locale")(*args)


def localedef(*args: str) -> ShipRunnable:
    """Execute POSIX utility "localedef"."""
    return prog("localedef")(*args)


def logger(*args: str) -> ShipRunnable:
    """Execute POSIX utility "logger"."""
    return prog("logger")(*args)


def logname(*args: str) -> ShipRunnable:
    """Execute POSIX utility "logname"."""
    return prog("logname")(*args)


def lp(*args: str) -> ShipRunnable:
    """Execute POSIX utility "lp"."""
    return prog("lp")(*args)


def ls(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ls"."""
    return prog("ls")(*args)


def m4(*args: str) -> ShipRunnable:
    """Execute POSIX utility "m4"."""
    return prog("m4")(*args)


def mailx(*args: str) -> ShipRunnable:
    """Execute POSIX utility "mailx"."""
    return prog("mailx")(*args)


def make(*args: str) -> ShipRunnable:
    """Execute POSIX utility "make"."""
    return prog("make")(*args)


def man(*args: str) -> ShipRunnable:
    """Execute POSIX utility "man"."""
    return prog("man")(*args)


def mesg(*args: str) -> ShipRunnable:
    """Execute POSIX utility "mesg"."""
    return prog("mesg")(*args)


def mkdir(*args: str) -> ShipRunnable:
    """Execute POSIX utility "mkdir"."""
    return prog("mkdir")(*args)


def mkfifo(*args: str) -> ShipRunnable:
    """Execute POSIX utility "mkfifo"."""
    return prog("mkfifo")(*args)


def more(*args: str) -> ShipRunnable:
    """Execute POSIX utility "more"."""
    return prog("more")(*args)


def mv(*args: str) -> ShipRunnable:
    """Execute POSIX utility "mv"."""
    return prog("mv")(*args)


def newgrp(*args: str) -> ShipRunnable:
    """Execute POSIX utility "newgrp"."""
    return prog("newgrp")(*args)


def nice(*args: str) -> ShipRunnable:
    """Execute POSIX utility "nice"."""
    return prog("nice")(*args)


def nl(*args: str) -> ShipRunnable:
    """Execute POSIX utility "nl"."""
    return prog("nl")(*args)


def nm(*args: str) -> ShipRunnable:
    """Execute POSIX utility "nm"."""
    return prog("nm")(*args)


def nohup(*args: str) -> ShipRunnable:
    """Execute POSIX utility "nohup"."""
    return prog("nohup")(*args)


def od(*args: str) -> ShipRunnable:
    """Execute POSIX utility "od"."""
    return prog("od")(*args)


def paste(*args: str) -> ShipRunnable:
    """Execute POSIX utility "paste"."""
    return prog("paste")(*args)


def patch(*args: str) -> ShipRunnable:
    """Execute POSIX utility "patch"."""
    return prog("patch")(*args)


def pathchk(*args: str) -> ShipRunnable:
    """Execute POSIX utility "pathchk"."""
    return prog("pathchk")(*args)


def pax(*args: str) -> ShipRunnable:
    """Execute POSIX utility "pax"."""
    return prog("pax")(*args)


def pr(*args: str) -> ShipRunnable:
    """Execute POSIX utility "pr"."""
    return prog("pr")(*args)


def printf(*args: str) -> ShipRunnable:
    """Execute POSIX utility "printf"."""
    return prog("printf")(*args)


def prs(*args: str) -> ShipRunnable:
    """Execute POSIX utility "prs"."""
    return prog("prs")(*args)


def ps(*args: str) -> ShipRunnable:
    """Execute POSIX utility "ps"."""
    return prog("ps")(*args)


def qalter(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qalter"."""
    return prog("qalter")(*args)


def qdel(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qdel"."""
    return prog("qdel")(*args)


def qhold(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qhold"."""
    return prog("qhold")(*args)


def qmove(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qmove"."""
    return prog("qmove")(*args)


def qmsg(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qmsg"."""
    return prog("qmsg")(*args)


def qrerun(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qrerun"."""
    return prog("qrerun")(*args)


def qrls(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qrls"."""
    return prog("qrls")(*args)


def qselect(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qselect"."""
    return prog("qselect")(*args)


def qsig(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qsig"."""
    return prog("qsig")(*args)


def qstat(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qstat"."""
    return prog("qstat")(*args)


def qsub(*args: str) -> ShipRunnable:
    """Execute POSIX utility "qsub"."""
    return prog("qsub")(*args)


def renice(*args: str) -> ShipRunnable:
    """Execute POSIX utility "renice"."""
    return prog("renice")(*args)


def rm(*args: str) -> ShipRunnable:
    """Execute POSIX utility "rm"."""
    return prog("rm")(*args)


def rmdel(*args: str) -> ShipRunnable:
    """Execute POSIX utility "rmdel"."""
    return prog("rmdel")(*args)


def rmdir(*args: str) -> ShipRunnable:
    """Execute POSIX utility "rmdir"."""
    return prog("rmdir")(*args)


def sact(*args: str) -> ShipRunnable:
    """Execute POSIX utility "sact"."""
    return prog("sact")(*args)


def sccs(*args: str) -> ShipRunnable:
    """Execute POSIX utility "sccs"."""
    return prog("sccs")(*args)


def sed(*args: str) -> ShipRunnable:
    """Execute POSIX utility "sed"."""
    return prog("sed")(*args)


def sleep(*args: str) -> ShipRunnable:
    """Execute POSIX utility "sleep"."""
    return prog("sleep")(*args)


def sort(*args: str) -> ShipRunnable:
    """Execute POSIX utility "sort"."""
    return prog("sort")(*args)


def split(*args: str) -> ShipRunnable:
    """Execute POSIX utility "split"."""
    return prog("split")(*args)


def strings(*args: str) -> ShipRunnable:
    """Execute POSIX utility "strings"."""
    return prog("strings")(*args)


def strip(*args: str) -> ShipRunnable:
    """Execute POSIX utility "strip"."""
    return prog("strip")(*args)


def stty(*args: str) -> ShipRunnable:
    """Execute POSIX utility "stty"."""
    return prog("stty")(*args)


def tabs(*args: str) -> ShipRunnable:
    """Execute POSIX utility "tabs"."""
    return prog("tabs")(*args)


def tail(*args: str) -> ShipRunnable:
    """Execute POSIX utility "tail"."""
    return prog("tail")(*args)


def talk(*args: str) -> ShipRunnable:
    """Execute POSIX utility "talk"."""
    return prog("talk")(*args)


def tee(*args: str) -> ShipRunnable:
    """Execute POSIX utility "tee"."""
    return prog("tee")(*args)


def time(*args: str) -> ShipRunnable:
    """Execute POSIX utility "time"."""
    return prog("time")(*args)


def touch(*args: str) -> ShipRunnable:
    """Execute POSIX utility "touch"."""
    return prog("touch")(*args)


def tput(*args: str) -> ShipRunnable:
    """Execute POSIX utility "tput"."""
    return prog("tput")(*args)


def tr(*args: str) -> ShipRunnable:
    """Execute POSIX utility "tr"."""
    return prog("tr")(*args)


def tsort(*args: str) -> ShipRunnable:
    """Execute POSIX utility "tsort"."""
    return prog("tsort")(*args)


def tty(*args: str) -> ShipRunnable:
    """Execute POSIX utility "tty"."""
    return prog("tty")(*args)


def uname(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uname"."""
    return prog("uname")(*args)


def uncompress(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uncompress"."""
    return prog("uncompress")(*args)


def unexpand(*args: str) -> ShipRunnable:
    """Execute POSIX utility "unexpand"."""
    return prog("unexpand")(*args)


def unget(*args: str) -> ShipRunnable:
    """Execute POSIX utility "unget"."""
    return prog("unget")(*args)


def uniq(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uniq"."""
    return prog("uniq")(*args)


def unlink(*args: str) -> ShipRunnable:
    """Execute POSIX utility "unlink"."""
    return prog("unlink")(*args)


def uucp(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uucp"."""
    return prog("uucp")(*args)


def uudecode(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uudecode"."""
    return prog("uudecode")(*args)


def uuencode(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uuencode"."""
    return prog("uuencode")(*args)


def uustat(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uustat"."""
    return prog("uustat")(*args)


def uux(*args: str) -> ShipRunnable:
    """Execute POSIX utility "uux"."""
    return prog("uux")(*args)


def val(*args: str) -> ShipRunnable:
    """Execute POSIX utility "val"."""
    return prog("val")(*args)


def vi(*args: str) -> ShipRunnable:
    """Execute POSIX utility "vi"."""
    return prog("vi")(*args)


def wc(*args: str) -> ShipRunnable:
    """Execute POSIX utility "wc"."""
    return prog("wc")(*args)


def what(*args: str) -> ShipRunnable:
    """Execute POSIX utility "what"."""
    return prog("what")(*args)


def who(*args: str) -> ShipRunnable:
    """Execute POSIX utility "who"."""
    return prog("who")(*args)


def write(*args: str) -> ShipRunnable:
    """Execute POSIX utility "write"."""
    return prog("write")(*args)


def xargs(*args: str) -> ShipRunnable:
    """Execute POSIX utility "xargs"."""
    return prog("xargs")(*args)


def yacc(*args: str) -> ShipRunnable:
    """Execute POSIX utility "yacc"."""
    return prog("yacc")(*args)


def zcat(*args: str) -> ShipRunnable:
    """Execute POSIX utility "zcat"."""
    return prog("zcat")(*args)

