#!/usr/bin/env python3
"""
Generate POSIX utility wrappers for ShipShell's ergo.posix module.

This script generates explicit function definitions for all POSIX standard
utilities (excluding shell built-ins) to provide IDE autocomplete support.
"""

# POSIX utilities that are shell built-ins (excluded from wrappers)
SHELL_BUILTINS = {
    "alias",
    "bg",
    "cd",
    "command",
    "echo",
    "exit",
    "false",
    "fc",
    "fg",
    "getopts",
    "hash",
    "jobs",
    "kill",
    "pwd",
    "read",
    "sh",
    "test",
    "true",
    "type",
    "ulimit",
    "umask",
    "unalias",
    "wait",
}

# All POSIX utilities from https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html
ALL_POSIX_UTILITIES = [
    "admin",
    "alias",
    "ar",
    "asa",
    "at",
    "awk",
    "basename",
    "batch",
    "bc",
    "bg",
    "c99",
    "cal",
    "cat",
    "cd",
    "cflow",
    "chgrp",
    "chmod",
    "chown",
    "cksum",
    "cmp",
    "comm",
    "command",
    "compress",
    "cp",
    "crontab",
    "csplit",
    "ctags",
    "cut",
    "cxref",
    "date",
    "dd",
    "delta",
    "df",
    "diff",
    "dirname",
    "du",
    "echo",
    "ed",
    "env",
    "ex",
    "expand",
    "expr",
    "false",
    "fc",
    "fg",
    "file",
    "find",
    "fold",
    "fort77",
    "fuser",
    "gencat",
    "get",
    "getconf",
    "getopts",
    "grep",
    "hash",
    "head",
    "iconv",
    "id",
    "ipcrm",
    "ipcs",
    "jobs",
    "join",
    "kill",
    "lex",
    "link",
    "ln",
    "locale",
    "localedef",
    "logger",
    "logname",
    "lp",
    "ls",
    "m4",
    "mailx",
    "make",
    "man",
    "mesg",
    "mkdir",
    "mkfifo",
    "more",
    "mv",
    "newgrp",
    "nice",
    "nl",
    "nm",
    "nohup",
    "od",
    "paste",
    "patch",
    "pathchk",
    "pax",
    "pr",
    "printf",
    "prs",
    "ps",
    "pwd",
    "qalter",
    "qdel",
    "qhold",
    "qmove",
    "qmsg",
    "qrerun",
    "qrls",
    "qselect",
    "qsig",
    "qstat",
    "qsub",
    "read",
    "renice",
    "rm",
    "rmdel",
    "rmdir",
    "sact",
    "sccs",
    "sed",
    "sh",
    "sleep",
    "sort",
    "split",
    "strings",
    "strip",
    "stty",
    "tabs",
    "tail",
    "talk",
    "tee",
    "test",
    "time",
    "touch",
    "tput",
    "tr",
    "true",
    "tsort",
    "tty",
    "type",
    "ulimit",
    "umask",
    "unalias",
    "uname",
    "uncompress",
    "unexpand",
    "unget",
    "uniq",
    "unlink",
    "uucp",
    "uudecode",
    "uuencode",
    "uustat",
    "uux",
    "val",
    "vi",
    "wait",
    "wc",
    "what",
    "who",
    "write",
    "xargs",
    "yacc",
    "zcat",
]

# Generate list of external utilities (excluding built-ins)
POSIX_EXTERNAL_UTILS = sorted(
    [util for util in ALL_POSIX_UTILITIES if util not in SHELL_BUILTINS]
)


def generate_module_code():
    """Generate the complete posix.py module code."""

    lines = [
        '"""',
        "POSIX utility wrappers for ergonomic shell scripting.",
        "",
        "This module provides wrapper functions for POSIX-standard external utilities,",
        "allowing concise command invocation without needing to use prog() explicitly.",
        "",
        "Usage:",
        "    from shp.ergo.posix import awk, grep, sed",
        "    ",
        "    # Before: prog('awk')('-F', ':', '{print $1}') ",
        "    # After:  awk('-F', ':', '{print $1}')",
        "",
        "Note: Shell built-ins like cd, pwd, exit are in shp.ergo.builtins instead.",
        "",
        "This file is auto-generated by tools/generate_posix_wrappers.py",
        '"""',
        "",
        "from shp import prog, ShipRunnable",
        "",
        "__all__ = [",
    ]

    # Add __all__ list
    for i, util in enumerate(POSIX_EXTERNAL_UTILS):
        comma = "," if i < len(POSIX_EXTERNAL_UTILS) - 1 else ""
        lines.append(f'    "{util}"{comma}')

    lines.append("]")
    lines.append("")
    lines.append("")

    # Generate function definitions
    for util in POSIX_EXTERNAL_UTILS:
        lines.extend(
            [
                f"def {util}(*args: str) -> ShipRunnable:",
                f'    """Execute POSIX utility "{util}"."""',
                f'    return prog("{util}")(*args)',
                "",
                "",
            ]
        )

    return "\n".join(lines)


def main():
    """Generate and write the posix.py module."""
    import os

    # Determine output path
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    output_path = os.path.join(project_root, "python", "shp", "ergo", "posix.py")

    # Generate code
    code = generate_module_code()

    # Write to file
    with open(output_path, "w") as f:
        f.write(code)

    print(f"Generated {len(POSIX_EXTERNAL_UTILS)} POSIX utility wrappers")
    print(f"Output written to: {output_path}")
    print(f"\nExcluded {len(SHELL_BUILTINS)} shell built-ins:")
    print(f"  {', '.join(sorted(SHELL_BUILTINS))}")


if __name__ == "__main__":
    main()
